#!/usr/bin/env python3
"""Generate the firmware backdrop (water/land bitmap) for any matrix size.

Rasterizes the coarse SF shoreline in server/geo.py at the requested pixel
size using the exact same projection as firmware/src/map_project.cpp, packs it
RLE, and writes firmware/src/backdrop.h. Regenerate after changing
PANEL_CHAIN_W/H:

    python3 tools/gen_backdrop.py --w 64 --h 32          # 1x1 panels
    python3 tools/gen_backdrop.py --w 128 --h 64         # 2x2 panels

Add --ppm out.ppm to also write a preview image (open with any image viewer,
or convert: sips -s format png out.ppm --out out.png).
"""

import argparse
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "server"))

from geo import BBOX, LAND_RGB, SF_LAND, WATER_RGB  # noqa: E402

HEADER = """#pragma once
// Auto-generated by tools/gen_backdrop.py — do not edit.
// RLE water/land bitmap, row-major: (count, colorIndex) byte pairs,
// 0 = land(2,2,2), 1 = water(0,0,0) — colors applied at render time in
// screen.h. Total pixels = BACKDROP_W * BACKDROP_H.

#define BACKDROP_W {w}
#define BACKDROP_H {h}

#ifdef ARDUINO
#include <pgmspace.h>
#else
#define PROGMEM
#endif
#include <stdint.h>

static const unsigned int backdrop_rle_len = {length};
static const uint8_t backdrop_rle[] PROGMEM = {{
{data}
}};
"""


def project_setup(width: int, height: int, stretch: bool = False):
    """Mirror MapProjection in firmware/src/map_project.h.

    stretch=False (default, matching MAP_STRETCH_TO_FILL 0) is the
    aspect-preserving centered fit; stretch=True maps the bbox onto the full
    display.
    """
    lat_span = BBOX["lat_max"] - BBOX["lat_min"]
    lon_span = BBOX["lon_max"] - BBOX["lon_min"]
    if stretch:
        return {"sx": width / lon_span, "sy": height / lat_span}
    mid_cos = math.cos((BBOX["lat_min"] + BBOX["lat_max"]) / 2 * math.pi / 180)
    lon_span_cos = lon_span * mid_cos
    scale = min(width / lon_span_cos, height / lat_span)
    return {
        "mid_cos": mid_cos, "scale": scale,
        "off_x": (width - lon_span_cos * scale) / 2,
        "off_y": (height - lat_span * scale) / 2,
    }


def pixel_to_latlon(width, height, px, py, stretch=False):
    setup = project_setup(width, height, stretch)
    if stretch:
        lon = BBOX["lon_min"] + (px + 0.5) / setup["sx"]
        lat = BBOX["lat_max"] - (py + 0.5) / setup["sy"]
    else:
        lon = BBOX["lon_min"] + (px + 0.5 - setup["off_x"]) / (setup["mid_cos"] * setup["scale"])
        lat = BBOX["lat_max"] - (py + 0.5 - setup["off_y"]) / setup["scale"]
    return lat, lon


def point_in_land(lat, lon):
    """Ray-casting test against the coarse shoreline polygon."""
    inside = False
    n = len(SF_LAND)
    j = n - 1
    for i in range(n):
        lat_i, lon_i = SF_LAND[i]
        lat_j, lon_j = SF_LAND[j]
        if (lon_i > lon) != (lon_j > lon):
            slope = (lat_j - lat_i) / (lon_j - lon_i)
            if lat < lat_i + slope * (lon - lon_i):
                inside = not inside
        j = i
    return inside


def rasterize(width, height, stretch=False):
    return [
        0 if point_in_land(*pixel_to_latlon(width, height, px, py, stretch)) else 1
        for py in range(height) for px in range(width)
    ]


def rle_encode(indices):
    runs = []
    current, count = None, 0
    for value in indices:
        if value == current:
            count += 1
        else:
            while count > 255:  # counts are uint8
                runs.append((255, current))
                count -= 255
            if count:
                runs.append((count, current))
            current, count = value, 1
    while count > 255:
        runs.append((255, current))
        count -= 255
    if count:
        runs.append((count, current))
    return runs


def write_ppm(path, width, height, indices):
    palette = {0: LAND_RGB, 1: WATER_RGB}
    with open(path, "wb") as fh:
        fh.write(f"P6 {width} {height} 255\n".encode())
        for index in indices:
            fh.write(bytes(palette[index]))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--w", type=int, default=64, help="total display width (px)")
    parser.add_argument("--h", type=int, default=32, help="total display height (px)")
    parser.add_argument("--out", type=Path, default=ROOT / "firmware/src/backdrop.h")
    parser.add_argument("--ppm", type=Path, default=None, help="also write a PPM preview")
    parser.add_argument("--stretch", action="store_true",
                        help="stretch the bbox to fill the display instead of the "
                             "default aspect-preserving fit (must match "
                             "MAP_STRETCH_TO_FILL in config.h)")
    args = parser.parse_args()

    indices = rasterize(args.w, args.h, stretch=args.stretch)
    runs = rle_encode(indices)
    data = ",\n".join(
        ", ".join(f"0x{count:02X},0x{color:02X}" for count, color in runs[i:i + 16])
        for i in range(0, len(runs), 16)
    )
    args.out.write_text(HEADER.format(w=args.w, h=args.h, length=len(runs) * 2, data=data))
    print(f"wrote {args.out} ({args.w}x{args.h}, {len(runs)} RLE runs)")

    if args.ppm:
        write_ppm(args.ppm, args.w, args.h, indices)
        print(f"wrote {args.ppm}")


if __name__ == "__main__":
    main()
